### ISSUE TITLE
Enforces Unspecified Rules - update eslint module

### ISSUE THREAD

**Issue by stuartstobie** [holidayextras/make-up#13]
At the moment make-up will produce errors for rules that are not specified in the config. This is because of eslint and was fixed in version 1.0.0 of the module. Can we update eslint to get around this?

**Comment by stuartstobie** [comment]
I've had a quick play with version 1.0.0 and 1.1.0 of eslint and it doesn't break any tests.

**Comment by hx-markterry** [comment]
We have now updated the version of eslint used, and our ruleset now contains all the new v1 rules
