### ISSUE TITLE
Linting node_modules

### ISSUE THREAD

**Issue by robhuzzey** [holidayextras/make-up#21]
Looking at this.. if you run it in command line without any arguments, it lints all files (which is sometimes what you want) but it also had issue because this means it will lint node_modules directory too!

I would like to see either an exclude flag `--exclude=` or by default it excludes node_modules directory?

**Comment by pmcnr-hx** [comment]
ESLint default behaviour is to exclude `node_modules`. I can't think of any scenario where `node_modules` should be linted so it should be excluded by default and if by any reason the user wants to include it they can add it explicitly to the list of directories to lint.

**Comment by philmeehan** [comment]
It's not doing that for me. If I run 
node_modules/.bin/make-up

inside this repo  https://github.com/holidayextras/plugin-cybersource

it only checks these files  [ './Gruntfile.js', './index.js', './temp.js' ]

You sure you are running the latest release?

**Comment by robhuzzey** [comment]
@philmeehan silly question... but you do have a node_modules dir in there when you run it right?

**Comment by robhuzzey** [comment]
@philmeehan I see the issue now... it failed for me when I ran `./node_modules/.bin/make-up ./` but... when I run `./node_modules/.bin/make-up` it defaults to only lint the files & no folders at the root.

@cameronviner that should solve your issue.
